import React from 'react';
import MenuItem from 'material-ui/MenuItem';

 export const stateNames = [
  <MenuItem key={1} value={1} primaryText="Alabama" />,
  <MenuItem key={2} value={2} primaryText="Alaska" />,
  <MenuItem key={3} value={3} primaryText="Arizona" />,
  <MenuItem key={4} value={4} primaryText="Arkansas" />,
  <MenuItem key={5} value={5} primaryText="California" />,
	<MenuItem key={6} value={6} primaryText="Colorado" />,
  <MenuItem key={7} value={7} primaryText="Connecticut" />,
  <MenuItem key={8} value={8} primaryText="Delaware" />,
  <MenuItem key={9} value={9} primaryText="Florida" />,
  <MenuItem key={10} value={10} primaryText="Georgia" />,
	<MenuItem key={11} value={11} primaryText="Hawaii" />,
  <MenuItem key={12} value={12} primaryText="Idaho" />,
  <MenuItem key={13} value={13} primaryText="Illinois" />,
  <MenuItem key={14} value={14} primaryText="Indiana" />,
  <MenuItem key={15} value={15} primaryText="Iowa" />,
	<MenuItem key={16} value={16} primaryText="Kansas" />,
  <MenuItem key={17} value={17} primaryText="Kentucky" />,
  <MenuItem key={18} value={18} primaryText="Louisiana" />,
  <MenuItem key={19} value={19} primaryText="Maine" />,
  <MenuItem key={20} value={20} primaryText="Maryland" />,
	<MenuItem key={21} value={21} primaryText="Massachussetts" />,
  <MenuItem key={22} value={22} primaryText="Michigan" />,
  <MenuItem key={23} value={23} primaryText="Minnesota" />,
  <MenuItem key={24} value={24} primaryText="Mississippi" />,
  <MenuItem key={25} value={25} primaryText="Missouri" />,
	<MenuItem key={26} value={26} primaryText="Montana" />,
  <MenuItem key={27} value={27} primaryText="Nebraska" />,
  <MenuItem key={28} value={28} primaryText="Nevada" />,
  <MenuItem key={29} value={29} primaryText="New Hampshire" />,
  <MenuItem key={30} value={30} primaryText="New Jersey" />,
	<MenuItem key={31} value={31} primaryText="New Mexico" />,
  <MenuItem key={32} value={32} primaryText="New York" />,
  <MenuItem key={33} value={33} primaryText="North Carolina" />,
  <MenuItem key={34} value={34} primaryText="North Dakota" />,
  <MenuItem key={35} value={35} primaryText="Ohio" />,
	<MenuItem key={36} value={36} primaryText="Oklahoma" />,
  <MenuItem key={37} value={37} primaryText="Oregon" />,
  <MenuItem key={38} value={38} primaryText="Pennsylvania" />,
  <MenuItem key={39} value={39} primaryText="Rhode Island" />,
  <MenuItem key={40} value={40} primaryText="South Carolina" />,
	<MenuItem key={41} value={41} primaryText="South Dakota" />,
  <MenuItem key={42} value={42} primaryText="Tennessee" />,
  <MenuItem key={43} value={43} primaryText="Texas" />,
  <MenuItem key={44} value={44} primaryText="Utah" />,
  <MenuItem key={45} value={45} primaryText="Vermont" />,
	<MenuItem key={46} value={46} primaryText="Virginia" />,
  <MenuItem key={47} value={47} primaryText="Washington" />,
  <MenuItem key={48} value={48} primaryText="West Virginia" />,
  <MenuItem key={49} value={49} primaryText="Wisconsin" />,
	<MenuItem key={50} value={50} primaryText="Wyoming" />,
];

export const stateList = [
{id: 1, name: "Alabama"},
{id: 2, name: "Alaska"},
{id: 3, name: "Arizona"},
{id: 4, name: "Arkansas"},
{id: 5, name: "California"},
{id: 6, name: "Colorado"},
{id: 7, name: "Connecticut"},
{id: 8, name: "Delaware"},
{id: 9, name: "Florida"},
{id: 10, name: "Georgia"},
{id: 11, name: "Hawaii"},
{id: 12, name: "Idaho"},
{id: 13, name: "Illinois"},
{id: 14, name: "Indiana"},
{id: 15, name: "Iowa"},
{id: 16, name: "Kansas"},
{id: 17, name: "Kentucky"},
{id: 18, name: "Louisiana"},
{id: 19, name: "Maine"},
{id: 20, name: "Maryland"},
{id: 21, name: "Massachussetts"},
{id: 22, name: "Michigan"},
{id: 23, name: "Minnesota"},
{id: 24, name: "Mississippi"},
{id: 25, name: "Missouri"},
{id: 26, name: "Montana"},
{id: 27, name: "Nebraska"},
{id: 28, name: "Nevada"},
{id: 29, name: "New Hampshire"},
{id: 30, name: "New Jersey"},
{id: 31, name: "New Mexico"},
{id: 32, name: "New York"},
{id: 33, name: "North Carolina"},
{id: 34, name: "North Dakota"},
{id: 35, name: "Ohio"},
{id: 36, name: "Oklahoma"},
{id: 37, name: "Oregon"},
{id: 38, name: "Pennsylvania"},
{id: 39, name: "Rhode Island"},
{id: 40, name: "South Carolina"},
{id: 41, name: "South Dakota"},
{id: 42, name: "Tennessee"},
{id: 43, name: "Texas"},
{id: 44, name: "Utah"},
{id: 45, name: "Vermont"},
{id: 46, name: "Virginia"},
{id: 47, name: "Washington"},
{id: 48, name: "West Virginia"},
{id: 49, name: "Wisconsin"},
{id: 50, name: "Wyoming"}
];


const states = [
"Alabama",
"Alaska",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachussetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada" ,
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Ohio",
"Oklahoma",
"Oregon" ,
"Pennsylvania",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming"
]
